<?php

namespace App\Http\Controllers;

use Inertia\Inertia;
use Inertia\Response;

class DataMappingController extends Controller
{
    public function index(): Response
    {
        return Inertia::render('platform/data-mappings', [
            'games' => $this->getGameMappings(),
        ]);
    }

    private function getGameMappings(): array
    {
        return [
            'fab' => [
                'name' => 'Flesh and Blood',
                'source' => 'fab-cards (The Fab Cube)',
                'sourceUrl' => 'https://github.com/the-fab-cube/fab-cards',
                'cardMappings' => [
                    ['source' => 'unique_id', 'target' => 'external_ids.fab_id', 'description' => 'Eindeutige Karten-ID'],
                    ['source' => 'name', 'target' => 'name', 'description' => 'Kartenname'],
                    ['source' => 'type_text', 'target' => 'type_line', 'description' => 'Typzeile'],
                    ['source' => 'types[]', 'target' => 'types', 'description' => 'Kartentypen'],
                    ['source' => 'traits[]', 'target' => 'subtypes', 'description' => 'Traits als Subtypen'],
                    ['source' => 'functional_text', 'target' => 'text', 'description' => 'Kartentext'],
                    ['source' => 'cost', 'target' => 'cost', 'description' => 'Ressourcenkosten'],
                    ['source' => 'power', 'target' => 'power', 'description' => 'Angriffswert'],
                    ['source' => 'defense', 'target' => 'defense', 'description' => 'Verteidigungswert'],
                    ['source' => 'health', 'target' => 'health', 'description' => 'Lebenspunkte (für Helden)'],
                    ['source' => 'pitch', 'target' => 'colors / game_specific.pitch', 'description' => 'Pitch-Wert → Farbe (1=Rot, 2=Gelb, 3=Blau)'],
                    ['source' => 'card_keywords[]', 'target' => 'keywords', 'description' => 'Keywords'],
                    ['source' => 'blitz_legal, cc_legal, ...', 'target' => 'legalities', 'description' => 'Format-Legalität'],
                    ['source' => 'intelligence', 'target' => 'game_specific.intelligence', 'description' => 'Intelligenz (Riptide)'],
                    ['source' => 'arcane', 'target' => 'game_specific.arcane', 'description' => 'Arcane Damage'],
                ],
                'printingMappings' => [
                    ['source' => 'unique_id', 'target' => 'external_ids.fab_printing_id', 'description' => 'Eindeutige Printing-ID'],
                    ['source' => 'set_id', 'target' => 'set_code', 'description' => 'Set-Code'],
                    ['source' => 'collector_number', 'target' => 'collector_number', 'description' => 'Sammlernummer'],
                    ['source' => 'rarity', 'target' => 'rarity / rarity_label', 'description' => 'Seltenheit (C, R, S, M, L, F, P, T)'],
                    ['source' => 'foiling', 'target' => 'finish', 'description' => 'Foiling (S=Standard, R=Rainbow, C=Cold, G=Gold Cold)'],
                    ['source' => 'art_variations[]', 'target' => 'finish (kombiniert)', 'description' => 'Art-Varianten (EA, AA, FA) → z.B. "R-EA"'],
                    ['source' => 'edition', 'target' => 'game_specific.edition', 'description' => 'Edition (A=Alpha, F=First, N=Normal, U=Unlimited)'],
                    ['source' => 'artists[]', 'target' => 'artist', 'description' => 'Künstler'],
                    ['source' => 'image_url', 'target' => 'image_url', 'description' => 'Bild-URL'],
                    ['source' => 'flavor_text', 'target' => 'flavor_text', 'description' => 'Flavor-Text'],
                    ['source' => 'tcgplayer_product_id', 'target' => 'game_specific.tcgplayer_product_id', 'description' => 'TCGPlayer ID'],
                ],
                'setMappings' => [
                    ['source' => 'id', 'target' => 'code / external_ids.fab_id', 'description' => 'Set-Code'],
                    ['source' => 'name', 'target' => 'name', 'description' => 'Set-Name'],
                    ['source' => 'set_type', 'target' => 'set_type', 'description' => 'Set-Typ'],
                    ['source' => 'release_date', 'target' => 'released_at', 'description' => 'Erscheinungsdatum'],
                    ['source' => 'card_count', 'target' => 'card_count', 'description' => 'Kartenanzahl'],
                    ['source' => 'edition', 'target' => 'game_specific.edition', 'description' => 'Edition'],
                ],
                'constants' => [
                    'rarities' => ['C' => 'Common', 'R' => 'Rare', 'S' => 'Super Rare', 'M' => 'Majestic', 'L' => 'Legendary', 'F' => 'Fabled', 'P' => 'Promo', 'T' => 'Token'],
                    'foilings' => ['S' => 'Standard', 'R' => 'Rainbow Foil', 'C' => 'Cold Foil', 'G' => 'Gold Cold Foil'],
                    'artVariations' => ['EA' => 'Extended Art', 'AA' => 'Alternate Art', 'FA' => 'Full Art'],
                    'editions' => ['A' => 'Alpha', 'F' => 'First Edition', 'N' => 'Normal', 'U' => 'Unlimited'],
                ],
                'notes' => [
                    'Karten mit gleichem Namen aber unterschiedlichem Pitch sind VERSCHIEDENE Karten',
                    'Printings werden durch set_id + collector_number + foiling + art_variations eindeutig identifiziert',
                    'Pitch-Wert bestimmt die "Farbe" der Karte (1=Rot, 2=Gelb, 3=Blau)',
                ],
            ],
            'mtg' => [
                'name' => 'Magic: The Gathering',
                'source' => 'Scryfall API',
                'sourceUrl' => 'https://scryfall.com/docs/api',
                'cardMappings' => [
                    ['source' => 'oracle_id', 'target' => 'external_ids.oracle_id', 'description' => 'Oracle ID (gleiche Karte über alle Printings)'],
                    ['source' => 'id', 'target' => 'external_ids.scryfall_id', 'description' => 'Scryfall ID'],
                    ['source' => 'name', 'target' => 'name', 'description' => 'Kartenname'],
                    ['source' => 'type_line', 'target' => 'type_line / types / subtypes / supertypes', 'description' => 'Typzeile (wird geparst)'],
                    ['source' => 'oracle_text', 'target' => 'text', 'description' => 'Oracle-Text'],
                    ['source' => 'mana_cost', 'target' => 'cost / game_specific.mana_cost', 'description' => 'Manakosten'],
                    ['source' => 'cmc', 'target' => 'game_specific.mana_value', 'description' => 'Converted Mana Cost'],
                    ['source' => 'power', 'target' => 'power', 'description' => 'Stärke'],
                    ['source' => 'toughness', 'target' => 'defense', 'description' => 'Widerstandskraft'],
                    ['source' => 'colors[]', 'target' => 'colors', 'description' => 'Farben (W, U, B, R, G)'],
                    ['source' => 'color_identity[]', 'target' => 'game_specific.color_identity', 'description' => 'Farbidentität (für Commander)'],
                    ['source' => 'keywords[]', 'target' => 'keywords', 'description' => 'Keywords'],
                    ['source' => 'legalities{}', 'target' => 'legalities', 'description' => 'Format-Legalität'],
                    ['source' => 'loyalty', 'target' => 'game_specific.loyalty', 'description' => 'Loyalität (Planeswalker)'],
                    ['source' => 'layout', 'target' => 'game_specific.layout', 'description' => 'Karten-Layout'],
                    ['source' => 'card_faces[]', 'target' => 'game_specific.card_faces', 'description' => 'Kartenseiten (DFC)'],
                ],
                'printingMappings' => [
                    ['source' => 'id', 'target' => 'external_ids.scryfall_id', 'description' => 'Scryfall ID (pro Printing)'],
                    ['source' => 'set', 'target' => 'set_code', 'description' => 'Set-Code'],
                    ['source' => 'set_name', 'target' => 'set_name', 'description' => 'Set-Name'],
                    ['source' => 'collector_number', 'target' => 'collector_number', 'description' => 'Sammlernummer'],
                    ['source' => 'rarity', 'target' => 'rarity / rarity_label', 'description' => 'Seltenheit'],
                    ['source' => 'finishes[]', 'target' => 'finish / game_specific.finishes', 'description' => 'Veredelung (nonfoil, foil, etched)'],
                    ['source' => 'lang', 'target' => 'language', 'description' => 'Sprache'],
                    ['source' => 'artist', 'target' => 'artist', 'description' => 'Künstler'],
                    ['source' => 'image_uris.normal', 'target' => 'image_url', 'description' => 'Bild-URL'],
                    ['source' => 'image_uris.small', 'target' => 'image_url_small', 'description' => 'Kleines Bild'],
                    ['source' => 'flavor_text', 'target' => 'flavor_text', 'description' => 'Flavor-Text'],
                    ['source' => 'prices{}', 'target' => 'prices.scryfall', 'description' => 'Preise (USD, EUR)'],
                    ['source' => 'promo', 'target' => 'is_promo', 'description' => 'Ist Promo'],
                    ['source' => 'reprint', 'target' => 'is_reprint', 'description' => 'Ist Nachdruck'],
                    ['source' => 'frame', 'target' => 'game_specific.frame', 'description' => 'Rahmen-Version'],
                    ['source' => 'border_color', 'target' => 'game_specific.border_color', 'description' => 'Rahmenfarbe'],
                    ['source' => 'full_art', 'target' => 'game_specific.is_full_art', 'description' => 'Full Art'],
                ],
                'setMappings' => [
                    ['source' => 'code', 'target' => 'code', 'description' => 'Set-Code'],
                    ['source' => 'name', 'target' => 'name', 'description' => 'Set-Name'],
                    ['source' => 'set_type', 'target' => 'set_type', 'description' => 'Set-Typ'],
                    ['source' => 'released_at', 'target' => 'released_at', 'description' => 'Erscheinungsdatum'],
                    ['source' => 'card_count', 'target' => 'card_count', 'description' => 'Kartenanzahl'],
                    ['source' => 'icon_svg_uri', 'target' => 'icon_url', 'description' => 'Set-Icon'],
                    ['source' => 'block', 'target' => 'game_specific.block', 'description' => 'Block-Zugehörigkeit'],
                ],
                'constants' => [
                    'rarities' => ['common' => 'Common', 'uncommon' => 'Uncommon', 'rare' => 'Rare', 'mythic' => 'Mythic Rare', 'special' => 'Special', 'bonus' => 'Bonus'],
                    'colors' => ['W' => 'White', 'U' => 'Blue', 'B' => 'Black', 'R' => 'Red', 'G' => 'Green'],
                ],
                'notes' => [
                    'oracle_id identifiziert die gleiche Karte über alle Printings hinweg',
                    'Scryfall ID ist pro Printing eindeutig',
                    'Type Line wird automatisch in types, subtypes und supertypes geparst',
                ],
            ],
            'onepiece' => [
                'name' => 'One Piece Card Game',
                'source' => 'Custom API',
                'sourceUrl' => null,
                'cardMappings' => [
                    ['source' => 'external_id / id', 'target' => 'external_ids.op_id', 'description' => 'Karten-ID'],
                    ['source' => 'name', 'target' => 'name', 'description' => 'Kartenname'],
                    ['source' => 'card_type', 'target' => 'types / game_specific.card_type', 'description' => 'Kartentyp (Leader, Character, Event, Stage)'],
                    ['source' => 'types[]', 'target' => 'subtypes', 'description' => 'Character-Typen'],
                    ['source' => 'effect', 'target' => 'text', 'description' => 'Effekt-Text'],
                    ['source' => 'cost', 'target' => 'cost', 'description' => 'Kosten'],
                    ['source' => 'power', 'target' => 'power', 'description' => 'Power'],
                    ['source' => 'life', 'target' => 'health / game_specific.life', 'description' => 'Leben (Leader)'],
                    ['source' => 'color', 'target' => 'colors / game_specific.color', 'description' => 'Hauptfarbe'],
                    ['source' => 'color_secondary', 'target' => 'colors / game_specific.color_secondary', 'description' => 'Nebenfarbe'],
                    ['source' => 'counter', 'target' => 'game_specific.counter', 'description' => 'Counter-Wert'],
                    ['source' => 'attribute', 'target' => 'game_specific.attribute', 'description' => 'Attribut'],
                    ['source' => 'trigger', 'target' => 'game_specific.trigger', 'description' => 'Trigger-Text'],
                ],
                'printingMappings' => [
                    ['source' => 'external_id / id', 'target' => 'external_ids.op_printing_id', 'description' => 'Printing-ID'],
                    ['source' => 'set_id / set', 'target' => 'set_code', 'description' => 'Set-Code'],
                    ['source' => 'collector_number / number', 'target' => 'collector_number', 'description' => 'Sammlernummer'],
                    ['source' => 'rarity', 'target' => 'rarity / rarity_label', 'description' => 'Seltenheit'],
                    ['source' => 'is_alternate_art', 'target' => 'finish / is_variant', 'description' => 'Alternate Art'],
                    ['source' => 'artist', 'target' => 'artist', 'description' => 'Künstler'],
                    ['source' => 'image_url', 'target' => 'image_url', 'description' => 'Bild-URL'],
                ],
                'setMappings' => [
                    ['source' => 'code / id', 'target' => 'code', 'description' => 'Set-Code'],
                    ['source' => 'name', 'target' => 'name', 'description' => 'Set-Name'],
                    ['source' => 'set_type', 'target' => 'set_type', 'description' => 'Set-Typ'],
                    ['source' => 'release_date', 'target' => 'released_at', 'description' => 'Erscheinungsdatum'],
                ],
                'constants' => [
                    'rarities' => ['L' => 'Leader', 'C' => 'Common', 'UC' => 'Uncommon', 'R' => 'Rare', 'SR' => 'Super Rare', 'SEC' => 'Secret Rare', 'SP' => 'Special', 'P' => 'Promo'],
                    'cardTypes' => ['Leader', 'Character', 'Event', 'Stage'],
                    'colors' => ['Red', 'Green', 'Blue', 'Purple', 'Black', 'Yellow'],
                ],
                'notes' => [
                    'Leader-Karten haben life statt power',
                    'Alternate Art Printings werden als separate Printings mit finish="alternate" gespeichert',
                ],
            ],
            'pokemon' => [
                'name' => 'Pokémon TCG',
                'source' => 'Pokémon TCG API',
                'sourceUrl' => 'https://pokemontcg.io/',
                'cardMappings' => [
                    ['source' => 'id', 'target' => 'external_ids.pokemon_tcg_id', 'description' => 'Pokémon TCG ID'],
                    ['source' => 'name', 'target' => 'name', 'description' => 'Kartenname'],
                    ['source' => 'supertype', 'target' => 'supertypes', 'description' => 'Supertyp (Pokémon, Trainer, Energy)'],
                    ['source' => 'subtypes[]', 'target' => 'subtypes', 'description' => 'Subtypen (Basic, Stage 1, etc.)'],
                    ['source' => 'types[]', 'target' => 'types / colors', 'description' => 'Pokémon-Typen'],
                    ['source' => 'rules[]', 'target' => 'text', 'description' => 'Regeltext'],
                    ['source' => 'attacks[]', 'target' => 'game_specific.attacks', 'description' => 'Attacken'],
                    ['source' => 'weaknesses[]', 'target' => 'game_specific.weaknesses', 'description' => 'Schwächen'],
                    ['source' => 'resistances[]', 'target' => 'game_specific.resistances', 'description' => 'Resistenzen'],
                    ['source' => 'retreatCost[]', 'target' => 'game_specific.retreat_cost', 'description' => 'Rückzugskosten'],
                    ['source' => 'hp', 'target' => 'health', 'description' => 'HP'],
                    ['source' => 'evolvesFrom', 'target' => 'game_specific.evolves_from', 'description' => 'Entwickelt sich von'],
                    ['source' => 'abilities[]', 'target' => 'game_specific.abilities', 'description' => 'Fähigkeiten'],
                ],
                'printingMappings' => [
                    ['source' => 'id', 'target' => 'external_ids.pokemon_printing_id', 'description' => 'Printing-ID'],
                    ['source' => 'set.id', 'target' => 'set_code', 'description' => 'Set-Code'],
                    ['source' => 'number', 'target' => 'collector_number', 'description' => 'Sammlernummer'],
                    ['source' => 'rarity', 'target' => 'rarity / rarity_label', 'description' => 'Seltenheit'],
                    ['source' => 'artist', 'target' => 'artist', 'description' => 'Künstler'],
                    ['source' => 'images.large', 'target' => 'image_url', 'description' => 'Bild-URL'],
                    ['source' => 'images.small', 'target' => 'image_url_small', 'description' => 'Kleines Bild'],
                    ['source' => 'flavorText', 'target' => 'flavor_text', 'description' => 'Flavor-Text'],
                    ['source' => 'tcgplayer.prices', 'target' => 'prices', 'description' => 'TCGPlayer Preise'],
                ],
                'setMappings' => [
                    ['source' => 'id', 'target' => 'code / external_ids.pokemon_set_id', 'description' => 'Set-ID'],
                    ['source' => 'name', 'target' => 'name', 'description' => 'Set-Name'],
                    ['source' => 'series', 'target' => 'game_specific.series', 'description' => 'Serie'],
                    ['source' => 'releaseDate', 'target' => 'released_at', 'description' => 'Erscheinungsdatum'],
                    ['source' => 'total', 'target' => 'card_count', 'description' => 'Kartenanzahl'],
                    ['source' => 'images.logo', 'target' => 'icon_url', 'description' => 'Set-Logo'],
                ],
                'constants' => [
                    'supertypes' => ['Pokémon', 'Trainer', 'Energy'],
                    'types' => ['Colorless', 'Darkness', 'Dragon', 'Fairy', 'Fighting', 'Fire', 'Grass', 'Lightning', 'Metal', 'Psychic', 'Water'],
                ],
                'notes' => [
                    'HP wird direkt als health gespeichert',
                    'Attacken werden als Array in game_specific gespeichert',
                ],
            ],
            'yugioh' => [
                'name' => 'Yu-Gi-Oh!',
                'source' => 'YGOPRODeck API',
                'sourceUrl' => 'https://ygoprodeck.com/api-guide/',
                'cardMappings' => [
                    ['source' => 'id', 'target' => 'external_ids.ygoprodeck_id', 'description' => 'YGOPRODeck ID'],
                    ['source' => 'name', 'target' => 'name', 'description' => 'Kartenname'],
                    ['source' => 'type', 'target' => 'types', 'description' => 'Kartentyp'],
                    ['source' => 'race', 'target' => 'subtypes', 'description' => 'Race/Subtyp'],
                    ['source' => 'desc', 'target' => 'text', 'description' => 'Beschreibung'],
                    ['source' => 'atk', 'target' => 'power', 'description' => 'ATK'],
                    ['source' => 'def', 'target' => 'defense', 'description' => 'DEF'],
                    ['source' => 'level', 'target' => 'game_specific.level', 'description' => 'Level'],
                    ['source' => 'attribute', 'target' => 'colors / game_specific.attribute', 'description' => 'Attribut'],
                    ['source' => 'archetype', 'target' => 'game_specific.archetype', 'description' => 'Archetyp'],
                    ['source' => 'linkval', 'target' => 'game_specific.link_value', 'description' => 'Link-Wert'],
                    ['source' => 'linkmarkers[]', 'target' => 'game_specific.link_markers', 'description' => 'Link-Marker'],
                    ['source' => 'scale', 'target' => 'game_specific.pendulum_scale', 'description' => 'Pendel-Skala'],
                    ['source' => 'banlist_info', 'target' => 'legalities', 'description' => 'Banlist-Status'],
                ],
                'printingMappings' => [
                    ['source' => 'card_sets[].set_code', 'target' => 'set_code', 'description' => 'Set-Code'],
                    ['source' => 'card_sets[].set_name', 'target' => 'set_name', 'description' => 'Set-Name'],
                    ['source' => 'card_sets[].set_rarity', 'target' => 'rarity / rarity_label', 'description' => 'Seltenheit'],
                    ['source' => 'card_sets[].set_rarity_code', 'target' => 'game_specific.rarity_code', 'description' => 'Seltenheits-Code'],
                    ['source' => 'card_sets[].set_price', 'target' => 'prices', 'description' => 'Preis'],
                    ['source' => 'card_images[].image_url', 'target' => 'image_url', 'description' => 'Bild-URL'],
                    ['source' => 'card_images[].image_url_small', 'target' => 'image_url_small', 'description' => 'Kleines Bild'],
                    ['source' => 'card_images[].image_url_cropped', 'target' => 'game_specific.image_url_cropped', 'description' => 'Cropped Bild'],
                ],
                'setMappings' => [
                    ['source' => 'set_code', 'target' => 'code', 'description' => 'Set-Code'],
                    ['source' => 'set_name', 'target' => 'name', 'description' => 'Set-Name'],
                    ['source' => 'tcg_date', 'target' => 'released_at', 'description' => 'TCG Erscheinungsdatum'],
                    ['source' => 'num_of_cards', 'target' => 'card_count', 'description' => 'Kartenanzahl'],
                ],
                'constants' => [
                    'attributes' => ['DARK', 'DIVINE', 'EARTH', 'FIRE', 'LIGHT', 'WATER', 'WIND'],
                    'types' => ['Effect Monster', 'Flip Effect Monster', 'Fusion Monster', 'Link Monster', 'Normal Monster', 'Pendulum Effect Monster', 'Ritual Monster', 'Spell Card', 'Synchro Monster', 'Trap Card', 'XYZ Monster'],
                ],
                'notes' => [
                    'Ein Kartenbild kann mehrere Printings in verschiedenen Sets haben',
                    'Banlist-Informationen werden als legalities gespeichert',
                ],
            ],
            'riftbound' => [
                'name' => 'Riftbound',
                'source' => 'Custom Import',
                'sourceUrl' => null,
                'cardMappings' => [
                    ['source' => 'id', 'target' => 'external_ids.riftbound_id', 'description' => 'Riftbound ID'],
                    ['source' => 'name', 'target' => 'name', 'description' => 'Kartenname'],
                    ['source' => 'type', 'target' => 'types', 'description' => 'Kartentyp'],
                    ['source' => 'subtype', 'target' => 'subtypes', 'description' => 'Subtyp'],
                    ['source' => 'text', 'target' => 'text', 'description' => 'Kartentext'],
                    ['source' => 'cost', 'target' => 'cost', 'description' => 'Kosten'],
                    ['source' => 'power', 'target' => 'power', 'description' => 'Power'],
                    ['source' => 'health', 'target' => 'health', 'description' => 'Health'],
                    ['source' => 'domain', 'target' => 'colors / game_specific.domain', 'description' => 'Domain'],
                ],
                'printingMappings' => [
                    ['source' => 'set_code', 'target' => 'set_code', 'description' => 'Set-Code'],
                    ['source' => 'collector_number', 'target' => 'collector_number', 'description' => 'Sammlernummer'],
                    ['source' => 'rarity', 'target' => 'rarity / rarity_label', 'description' => 'Seltenheit'],
                    ['source' => 'image_url', 'target' => 'image_url', 'description' => 'Bild-URL'],
                ],
                'setMappings' => [
                    ['source' => 'code', 'target' => 'code', 'description' => 'Set-Code'],
                    ['source' => 'name', 'target' => 'name', 'description' => 'Set-Name'],
                ],
                'constants' => [
                    'domains' => ['Fury', 'Calm', 'Mind', 'Body', 'Chaos', 'Order'],
                ],
                'notes' => [],
            ],
        ];
    }
}
